[build]
  command = "./build.sh"
  publish = "view"

[functions]
  directory = "backend"
  included_files = ["config/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/goapi/api/:splat"
  status = 200